# web_app/Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Salin package.json untuk install dependencies
COPY package*.json ./

# Install dependencies. `postinstall` akan berjalan di sini dan berhasil.
RUN npm install

# Expose port
EXPOSE 3000

# Perintah default untuk menjalankan server development
CMD ["npm", "run", "dev"]