# web_app/Dockerfile.dev (File BARU)
FROM node:18-alpine

WORKDIR /app

# Salin package.json untuk install dependencies
COPY package*.json ./

# Cukup install dependencies. Kode akan di-mount dari 'volumes'.
RUN npm install

# Expose port
EXPOSE 3000

# Perintah default untuk menjalankan server development
CMD ["npm", "run", "dev"]